# Site settings
title: The First UK AI Conference 2023 - Turing AI Fellowship Event
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the web page of the First UK AI Conference 2023 - Turing AI Fellowship Event.
baseurl: "/ukai2023" # the subpath of your site, e.g. /blog/
url: "http://uk-ai.org" # the base hostname & protocol for your site
github_username:  uk-ai


youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: ukai2023
  
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme

remote_theme: uk-ai/jekyll-theme

# Build settings
future: true


analytics:
 google:
   tracking_id: # Google tracking ID if applicable

youtube:
  height: 315
  width: 560


collections:
  sessions:
    output: true
    permalink: "/:categories/:title.html"

